let respostas=[];const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function avg(k){if(!respostas.length)return '–';return (respostas.reduce((a,r)=>a+(+r[k]||0),0)/respostas.length).toFixed(1)}
function counts(k){return respostas.reduce((o,r)=>{const v=r[k]||'Não informado';o[v]=(o[v]||0)+1;return o},{})}
function bars(el,obj){const max=Math.max(1,...Object.values(obj));el.innerHTML=Object.entries(obj).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="barrow"><span>${esc(k)}</span><div class="track"><div class="fill" style="width:${v/max*100}%"></div></div><b>${v}</b></div>`).join('')||'<span class="empty">Sem dados</span>'}
function render(){
 $('#total').textContent=respostas.length;$('#mediaQualidade').textContent=avg('qualidade')+'/5';$('#mediaVariedade').textContent=avg('variedade')+'/5';$('#mediaAtendimento').textContent=avg('atendimento')+'/5';$('#mediaLimpeza').textContent=avg('limpeza')+'/5';$('#mediaCusto').textContent=avg('custo_beneficio')+'/5';$('#mediaRec').textContent=avg('recomendacao');
 bars($('#sobremesaCompra'),counts('compraria_sobremesa'));bars($('#frequencia'),counts('frequencia'));bars($('#recomendacao'),counts('recomendacao'));
 const sc={};respostas.forEach(r=>{try{JSON.parse(r.sobremesas||'[]').forEach(x=>sc[x]=(sc[x]||0)+1)}catch{}if(r.sobremesa_outra)sc['Outra: '+r.sobremesa_outra]=(sc['Outra: '+r.sobremesa_outra]||0)+1});bars($('#sobremesas'),sc);renderTable(respostas)
}
function renderTable(arr){$('#tbody').innerHTML=arr.map(r=>`<tr><td>${esc((r.criado_em||'').replace('T',' '))}</td><td>${r.qualidade}</td><td>${r.variedade}</td><td>${r.atendimento}</td><td>${r.limpeza}</td><td>${r.custo_beneficio}</td><td>${r.recomendacao}</td><td>${esc(r.prato_favorito)}</td><td>${esc(r.prato_desejado)}</td><td>${esc(r.compraria_sobremesa)}</td><td>${esc(r.comentario)}</td></tr>`).join('')||'<tr><td colspan="11" class="empty">Nenhuma resposta ainda.</td></tr>'}
async function load(){ $('#loading').hidden=false;$('#errorPanel').hidden=true;try{const r=await fetch('/api/painel',{cache:'no-store'});if(!r.ok)throw new Error(r.status===401?'Acesso não autorizado.':'Não foi possível carregar os resultados.');const d=await r.json();respostas=d.respostas||[];render();$('#dashboard').hidden=false;$('#loading').hidden=true}catch(e){$('#loading').hidden=true;$('#errorPanel').textContent=e.message;$('#errorPanel').hidden=false}}
$('#refresh').onclick=load;$('#busca').addEventListener('input',e=>{const q=e.target.value.toLowerCase();renderTable(respostas.filter(r=>JSON.stringify(r).toLowerCase().includes(q)))});load();
